# Callsigns
alias = 0.1         # Replaced by position with user alias
able = 0.1
baker = 0.1
cinnamon = 0.1
dagger = 0.1
eagle = 0.1
feline = 0.1
gantry = 0.1
hog = 0.1
icy = 0.1
joker = 0.1
kale = 0.1
longbow = 0.1
misfit = 0.1
nitro = 0.1
polaris = 0.1
reach = 0.1
simple = 0.1
tempest = 0.1
vulcan = 0.1

# BRAA/Bullseye
bra = 0.1
bullseye = 0.1
for = 0.1
at = 0.1
thousand = 0.1
hot = 0.1
flanking = 0.1
beaming = 0.1
cold = 0.1
hostile = 0.1
track = 0.1
north = 0.1
northeast = 0.1
east = 0.1
southeast = 0.1
south = 0.1
southwest = 0.1
west = 0.1
northwest = 0.1

# Mission-specific
caution = 0.1
s = 0.1
a = 0.1
threat = 0.1
radar = 0.1
negative = 0.1
contact = 0.1
standby = 0.1
single = 0.1
f = 0.1
j = 0.1
plus = 0.1
minus = 0.1

# Numbers
decimal = 0.1
zero = 0.1
one = 0.1
two = 0.1
three = 0.1
four = 0.1
five = 0.1
six = 0.1
seven = 0.1
eight = 0.1
niner = 0.1
ten = 0.1
eleven = 0.1
twelve = 0.1
thirteen = 0.1
fourteen = 0.1
fifteen = 0.1
sixteen = 0.1
seventeen = 0.1
eighteen = 0.1
nineteen = 0.1