# Callsigns
alias = 0.05         # Replaced by position with user alias
able = 0.05
baker = 0.05
cinnamon = 0.05
dagger = 0.05
eagle = 0.05
feline = 0.05
gantry = 0.05
hog = 0.05
icy = 0.05
joker = 0.05
kale = 0.05
longbow = 0.05
misfit = 0.05
nitro = 0.05
polaris = 0.05
reach = 0.05
simple = 0.05
tempest = 0.05
vulcan = 0.05

# BRAA/Bullseye
bra = 0.05
bullseye = 0.05
for = 0.05
at = 0.05
thousand = 0.05
hot = 0.05
flanking = 0.05
beaming = 0.05
cold = 0.05
hostile = 0.05
track = 0.05
north = 0.05
northeast = 0.05
east = 0.05
southeast = 0.05
south = 0.05
southwest = 0.05
west = 0.05
northwest = 0.05

# Mission-specific
caution = 0.05
s = 0.01
a = 0.01
threat = 0.05
radar = 0.05
negative = 0.05
contact = 0.05
standby = 0.05
single = 0.05
f = 0.01
j = 0.01
plus = 0.05
minus = 0.05

# Numbers
decimal = 0.05
zero = 0.05
one = 0.05
two = 0.05
three = 0.05
four = 0.05
five = 0.05
six = 0.05
seven = 0.05
eight = 0.05
niner = 0.05
ten = 0.05
eleven = 0.05
twelve = 0.05
thirteen = 0.05
fourteen = 0.05
fifteen = 0.05
sixteen = 0.05
seventeen = 0.05
eighteen = 0.05
nineteen = 0.05